### ISSUE TITLE
xmobar displays error for volume plugin after unlocking session

### ISSUE THREAD

**Issue by obszczymucha** [jaor/xmobar#215]
Volume plugin is installed and working fine - it displays value properly and responds to keybinds.

However, when I lock the session and unlock it, I see the following message instead of volume percentage:
`error: AlsaException.Cons "snd_mixer_attach" "No such file or directory" (Errno 2)`

The error disappears after reloading xmonad (therefore xmobar too).
It's just an issue with refreshing the status, because keybinds for increasing/decreasing volume still work while error is displayed.

Screenshot of the error: http://i.imgur.com/bGCLKgQ.png

**Comment by jaor** [comment]
this is probably happening because during wake-up xmobar tries to read a not-yet-restored virtual file (snd_mixer_attach)... i'll take a look when i find a moment, unless someone else beats me to it :)

**Comment by jaor** [comment]
@obszczymucha i've just pushed a patch to the master branch that tries to be a bit more careful catching errors in the volume plugin.  if you're able to compile xmobar from git and try it, please let me know whether it helps.  thanks!

**Comment by mateuszmnm** [comment]
Wow! Thank you! I'll try compiling it tomorrow and post the results.

**Comment by obszczymucha** [comment]
Wow! Thank you! I'll try compiling it tomorrow and post the results.

**Comment by mateuszmnm** [comment]
I've compiled the latest source and unfortunately the issue is still there.

**Comment by obszczymucha** [comment]
I've compiled the latest source and unfortunately the issue is still there.

**Comment by jaor** [comment]
@obszczymucha i've pushed yet another patch trying to tighten exception handling in the volume plugin. please let me know if it helps in any way.  thanks a lot for your patience!

**Comment by obszczymucha** [comment]
@jaor This fixed it! Thank you!!
